### ISSUE TITLE
Fix primary key secondary key table overwrites

### ISSUE THREAD

**Issue by bigsnarfdude** [snowplow/spark-streaming-example-project#16]
there appears to be more raw logs and less aggregations written to DynamoDB table AggregateRecords.
I suspect that I changed the schema last week from "downsampled_bucket_time + createdAt_timestamp"  to the new  "downsampled_bucket_time + color" which would potentially result in less uniqueness at the table level.  maybe the keys are overwriting each other resulting in less aggregations written to AggregateRecords.

**Comment by alexanderdean** [comment]
Hey @bigsnarfdude - I've done some further thinking on this. To recap, what we want is a composite key consisting of timebucket + event type. This is so that if you want to get metrics on e.g. "Blue", you can just do a scan of Blue records, for the timebuckets you care about.

You are correct - your current approach won't deliver the above. This is because you will accidentally overwrite your existing count with the new count.

The solution is not to change the secondary index to a whenwritten timestamp, because then we end up with multiple records for a given timebucket+eventtype, and we lose the secondary indexing on event type.

The solution instead is a simple one. We do a _read_ on the existing timebucket+eventtype key, and add our new count to the existing count if found; if not found then we just write the new count.

Does that make sense? Here is the pseudo-code:

```
for each [timebucket, eventtype, count]:
  get old_count from dynamodb for timebucket+eventtype
  if old_count is null
    new_count = count
  else
    new_count = old_count + count
  end
  write new_count to dynamodb for timebucket+eventtype
end
```

Please confirm the above makes sense and you can make that change on Monday.

**Comment by bigsnarfdude** [comment]
somehow my branch got merged to master. i can't recall if i did that but, I tried to revert master and failed. i don't know how to rebase. i could reset my local master three stops and branch off the master at:

commit de1a7e312fcd18dccbfeb91c5cb14bd2e45bba21
Author: Alex Dean alex@snowplowanalytics.com
Date:   Sat Jun 6 12:55:09 2015 +0100

```
Working on the build Spark
```

**Comment by alexanderdean** [comment]
Delete your local copy, do a fresh checkout of master, branch from there...

**Comment by alexanderdean** [comment]
(I merged your branch to master and deleted it to prevent confusion!)

**Comment by bigsnarfdude** [comment]
ok

**Comment by bigsnarfdude** [comment]
getOrCreate function built to resolve overwrites
